# Generated by Django 5.1.6 on 2025-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0003_remove_artisttable_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artisttable",
            name="art_cat",
        ),
        migrations.AddField(
            model_name="artisttable",
            name="art_categories",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
