# Generated by Django 5.1.6 on 2025-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0004_remove_artisttable_art_cat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisttable",
            name="art_categories",
            field=models.CharField(default="", max_length=255),
        ),
    ]
