# Generated by Django 5.1.6 on 2025-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0005_alter_artisttable_art_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisttable",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
