# Generated by Django 5.1.6 on 2025-02-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0006_artisttable_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='art_photos/')),
            ],
        ),
    ]
