# Generated by Django 5.1.6 on 2025-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0008_delete_usertable_remove_artisttable_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=30)),
            ],
        ),
    ]
