# Generated by Django 5.1.6 on 2025-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0009_usertable"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisttable",
            name="userid",
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
