# Generated by Django 5.1.6 on 2025-02-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0011_arttable_status_arttable_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertable",
            name="status",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
