# Generated by Django 5.1.6 on 2025-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0012_usertable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="arttable",
            name="arttype",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
