# Generated by Django 5.1.6 on 2025-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0013_arttable_arttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=30)),
                ("user_id", models.CharField(max_length=30)),
                ("product_id", models.CharField(max_length=30)),
                ("date", models.CharField(max_length=30)),
                ("delivery_date", models.CharField(max_length=30)),
                ("delivery_address", models.CharField(max_length=30)),
                ("payment_status", models.CharField(max_length=30)),
                ("delivery_status", models.CharField(max_length=30)),
            ],
        ),
    ]
