# Generated by Django 5.1.6 on 2025-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0014_ordertable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertable",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
