# Generated by Django 5.1.6 on 2025-03-08 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("art_app", "0015_alter_ordertable_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertable",
            name="payment_status",
        ),
    ]
